import postcss from 'postcss';
require("./fix-ugly-functions");
import imports from 'postcss-import';
import fixFontDeclarations from './fix-font-declarations';
import colorFunctions from './color-functions';
colorFunctions();
import gtkColorVariables from './color-variables';
import gtkPseudoClasses from './psuedo-classes';
import valueHook from './value-hook';
import functions from 'postcss-functions';

const gtkFunctions = functions({
    functions : {
        "image": (...args) => {
            if (args.length === 1) {
                return `linear-gradient(${args[0]}, ${args[0]})`;
            }
        },
        "linear-gradient": (...args) => {
            if (args.length === 1) {
                return `linear-gradient(${args[0]}, ${args[0]})`;
            } else {
                return `linear-gradient(${args.join(',')})`;
            }
        },
        "from": color => color,
        "to": color => color,
        "color-stop": (stop, color) => `${color} ${stop*100}%`,
        "-gtk-gradient": (...args) => {
            console.log(args);
            return `linear-gradient(${args.slice(3).join(',')})`;
        },
        "-gtk-scaled": (...args) => {
            return args[0];
        },
        "-gtk-recolor": (...args) => {
            return args[0];
        }
    }
});

export default postcss([imports(), fixFontDeclarations, gtkColorVariables, gtkPseudoClasses, valueHook, gtkFunctions])
// Generated by CoffeeScript 2.2.3
/* (function() {
  var fixFontDeclarations, gtkColorVariables, gtkPseudoClasses, imports, postcss, valueHook;

  postcss = require("postcss");

  require("./fix-ugly-functions");

  imports = require("postcss-import");

  fixFontDeclarations = require("./fix-font-declarations");

  gtkColorVariables = require("./color-variables");

  require("./color-functions");

  gtkPseudoClasses = require("./psuedo-classes");

  valueHook = require("./value-hook");

  module.exports = postcss([imports(), fixFontDeclarations, gtkColorVariables, gtkPseudoClasses, valueHook]);

}).call(this); */
