// Generated by CoffeeScript 2.2.3

import * as postcss from "postcss";

// @FIXME don't use a global list
const valueHooks = [];

export default postcss.plugin('gtk-color-variables', () => (css, processor) => css.walkDecls((decl) => {
    return (decl.value = hook(decl.value, decl));
}));

export function hook(value, node) {
    if (value === '') {
        return value;
    }
    for (let i = 0; i < valueHooks.length; i++) {
        const fn = valueHooks[i];
        value = fn(value, node);
        if (typeof value !== 'string') {
            throw new Error(`Value hook returned ${typeof value}`);
        }
    }
    return value;
}

export function add(hook) {
    return valueHooks.push(hook);
}
